@extends("layouts.mysite")

<table>
    <thead>
        <tr>
            <td>yo</td>
            <td>yo</td>
            <td>yo</td>
            <td>yo</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>yo</td>
            <td>yo</td>
            <td>yo</td>
            <td>yo</td>
        </tr>
    </tbody>
</table>